#!/usr/bin/env python3
"""
Claude Code 格式转换器

将 SKILL.md 转换为 Claude Code commands 格式
"""

import sys
from pathlib import Path


def convert(skill_path: Path) -> str:
    """
    转换 skill 到 Claude Code 格式

    Claude Code commands 是简单的 .md 文件，
    不需要 frontmatter，直接使用内容部分。
    """
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return ""

    content = skill_file.read_text(encoding="utf-8")

    # 移除 frontmatter
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            content = parts[2].strip()

    # Claude Code commands 格式
    # 添加简化的头部说明
    output = f"""# {skill_path.name}

{content}

---
Auto-generated by skill-sync from {skill_path.name}
"""
    return output


def main():
    if len(sys.argv) < 2:
        print("Usage: claude.py <skill_path>", file=sys.stderr)
        sys.exit(1)

    skill_path = Path(sys.argv[1])
    result = convert(skill_path)
    print(result)


if __name__ == "__main__":
    main()
