#!/usr/bin/env python3
"""
OpenCode 格式转换器

将 SKILL.md 转换为 OpenCode AGENTS.md 格式
"""

import sys
from pathlib import Path


def convert(skill_path: Path) -> str:
    """
    转换 skill 到 OpenCode 格式
    
    OpenCode 使用 AGENTS.md 作为指令文件，
    格式与 SKILL.md 类似，但需要调整一些语法。
    """
    skill_file = skill_path / "SKILL.md"
    if not skill_file.exists():
        return ""

    content = skill_file.read_text(encoding="utf-8")

    # 解析 frontmatter
    metadata = {}
    if content.startswith("---"):
        parts = content.split("---", 2)
        if len(parts) >= 3:
            fm_text = parts[1].strip()
            for line in fm_text.split("\n"):
                if ":" in line:
                    key, value = line.split(":", 1)
                    metadata[key.strip()] = value.strip().strip('"')
            content = parts[2].strip()

    # OpenCode AGENTS.md 格式
    name = metadata.get("name", skill_path.name)
    description = metadata.get("description", "")

    output = f"""# {name}

> {description}

{content}

---
<!-- Auto-generated by skill-sync from {skill_path.name} -->
<!-- Source: {skill_path} -->
"""
    return output


def main():
    if len(sys.argv) < 2:
        print("Usage: opencode.py <skill_path>", file=sys.stderr)
        sys.exit(1)

    skill_path = Path(sys.argv[1])
    result = convert(skill_path)
    print(result)


if __name__ == "__main__":
    main()