#!/usr/bin/env python3
"""Classify flat skills into category subdirectories based on name keywords.

A "flat skill" is a directory directly under collection/skills/ that contains
a SKILL.md file.  Directories that do NOT contain SKILL.md are treated as
category containers and skipped.
"""

import os
import subprocess
from collections import defaultdict
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "collection" / "skills"
REPO_ROOT = Path(__file__).resolve().parent.parent

# Category directories to exclude from classification
CATEGORY_DIRS = {
    "agent-tools",
    "ai-ml",
    "ai-safety-eval",
    "chat-history-lancedb",
    "continual-learning",
    "control-systems",
    "data-retrieval",
    "deployment-optimization",
    "finance",
    "general-ml",
    "healthcare-bio",
    "knowledge-graph",
    "math-statistics",
    "medical",
    "memory",
    "multi-agent-rl",
    "neuroscience",
    "nlp-llm",
    "other",
    "physics-math",
    "quantum",
    "reasoning-bayesian",
    "reinforcement-learning",
    "security-privacy",
    "signal-control-systems",
    "skill-rag-indexer",
    "software-engineering",
    "spiking-neuromorphic",
    "systems-engineering",
    "tools-frameworks",
    "vision-generative",
}

# Non-skill files
NON_SKILL = {"README.md", "SKILL.md", "_INDEX.json", "INDEX.md", "DESCRIPTION.md"}

# Keyword-based classification rules: (keywords, category)
# Ordered by specificity - first match wins
CLASSIFICATION_RULES = [
    # === Neuroscience ===
    (
        [
            "fnirs",
            "optical-brain",
            "brain-connectivity",
            "brain-network",
            "brain-age",
            "brain-dynamics",
            "brain-state",
            "brain-wave",
            "brain-visual-cortex",
            "brain-functional",
            "brain-topological",
            "brain-alignment",
            "brain-language",
            "brain-encoding",
            "brain-network-communication",
            "brain-critical",
            "eeg-",
            "eeg-foundation",
            "meg-",
            "meg-decoding",
            "fmri-",
            "fmri-foundation",
            "neuroimaging",
            "neurofeedback",
            "neurotech",
            "neural-dynamics",
            "neural-decoding",
            "neural-encoding",
            "neural-activity",
            "neural-population",
            "neural-trajectory",
            "neural-manifold",
            "neural-representation",
            "neural-computation",
            "neural-mechanisms",
            "neural-synchrony",
            "neural-oscillation",
            "neurocognitive",
            "neurocomputational",
            "cortical",
            "hippocamp",
            "cerebellar",
            "thalam",
            "connectome",
            "connectivity",
            "resting-state",
            "bold-signal",
            "neural-networks-dynamical",
            "neural-field",
            "olfactory",
            "visual-cortex",
            "auditory-cortex",
            "prefrontal",
            "motor-cortex",
            "somatosensory",
            "brain-diffusion",
            "brain-language",
            "neuromodulation",
            "neurosteroid",
            "tms-",
            "tdcs",
            "brain-stimulation",
            "ecog",
            "ecog-",
            "intracranial-eeg",
            "seeg",
            "mind-omni",
            "neuro-adaptive",
            "neuroergonomic",
            "cognition",
            "cognitive-load",
            "cognitive-control",
            "neurogenesis",
            "neurodegenerative",
            "alzheimer",
            "parkinson",
            "epilepsy",
            "dementia",
            "behavioral",
            "behavioural",
            "psychosis",
            "sleep-stage",
            "dream-",
            "memory-consolidation",
            "neuropsychiatric",
            "neurodevelopmental",
            "brain-computer",
            "bci-",
            "bci-for",
            "brain-stimulation",
            "neuro-privacy",
            "neuro-symbolic",
            "neuro-symbolic",
            "tribe-v2",
            "tribev2",
            "beast3d",
            "whisper-ecog",
        ],
        "neuroscience",
    ),
    # === Quantum ===
    (
        [
            "quantum-",
            "-quantum",
            "qubit",
            "qec-",
            "qaoa-",
            "qpe-",
            "vqe-",
            "clifford",
            "entanglement",
            "qldpc",
            "superconducting",
            "trapped-ion",
            "qml-",
            "qcnn",
            "qnn-",
            "qgan-",
            "tensor-network",
            "tensor-network-",
            "quantum-error",
            "quantum-control",
            "quantum-circuit",
            "quantum-state",
            "quantum-measurement",
            "quantum-annealing",
            "quantum-gate",
            "quantum-algorithm",
            "quantum-optimization",
            "quantum-machine-learning",
            "quantum-information",
            "quantum-computing",
            "quantum-neural",
            "quantum-enhanced",
            "quantum-foundation",
            "quantum-ground-state",
            "quantum-kernel",
            "quantum-phase",
            "quantum-chemistry",
            "quantum-simulation",
            "qfi-",
            "qec-formal",
            "qec-",
            "quantum-circuit-learning",
            "quantum-fisher",
            "quantum-metrology",
            "quantum-sensing",
            "quantum-walk",
            "quantum-speckle",
            "quantum-ldpc",
            "quantum-topological",
            "quantum-compiler",
            "quantum-transpiler",
            "quantum-error-mitigation",
            "qem-",
            "quantum-many-body",
            "quantum-monte-carlo",
            "quantum-federated",
            "quantum-cryptography",
            "quantum-key-distribution",
            "quantum-communication",
            "quantum-teleportation",
            "quantum-transport",
            "quantum-heat-engine",
            "quantum-thermo",
            "quantum-battery",
            "quantum-data-center",
            "quantum-random",
            "quantum-gravity",
            "quantum-cosmology",
            "quantum-biology",
            "quantum-brain",
            "quantum-memory",
            "quantum-network",
            "quantum-non-demolition",
            "quantum-faraday",
            "quantum-readout",
            "quantum-hybrid",
            "quantum-retrieval",
            "quantum-radar",
            "quantum-limit",
            "quantum-enhanced",
            "quantum-wireless",
            "quantum-electromagnetics",
            "quantum-finance",
            "quantum-economic",
            "quantum-discord",
            "quantum-metabolic",
            "quantum-fisher",
            "quantum-native",
            "quantum-hamiltonian",
            "quantum-resonance",
            "quantum-rare-event",
            "quantum-thermal",
            "quantum-state-engineering",
            "quantum-cell",
            "quantum-genetic",
            "quantum-process-tomography",
            "non-hermitian-quantum",
            "open-quantum",
            "topological-quantum",
            "quantum-chaos",
            "quantum-relativistic",
            "quantum-stabilizer",
            "quantum-holographic",
            "quantum-graph",
            "quantum-rademacher",
            "quantum-neural-measurement",
            "quantum-generative-adversarial",
            "quantum-encoding",
            "quantum-steerability",
            "qnd-measurement",
            "qcnn-parallel",
            "quantum-young-measure",
            "qec-rademacher",
            "qubo-",
        ],
        "quantum",
    ),
    # === Spiking & Neuromorphic ===
    (
        [
            "spiking-",
            "-spiking",
            "snn-",
            "-snn",
            "neuromorphic",
            "snngp",
            "spike-",
            "if-neuron",
            "lif-neuron",
            "event-driven",
            "spike-timing",
            "stdp",
            "spike-driven",
            "spiking-transformer",
            "pcnn",
            "spike-image",
            "spike-nvpt",
            "lateral-inhibition",
            "snn-acceleration",
            "clane-neuromorphic",
            "xoresnet",
            "neuro-burst",
            "temporal-coding",
            "unispike",
            "vencircuit",
            "ven-circuit",
            "transport-mean-field-snn",
            "globally-optimal-snn",
            "clockless-neuromorphic",
        ],
        "spiking-neuromorphic",
    ),
    # === NLP & LLM ===
    (
        [
            "llm-",
            "-llm",
            "language-model",
            "transformer-",
            "-transformer",
            "gpt-",
            "bert-",
            "nlp-",
            "text-generation",
            "prompt-",
            "rag-",
            "retrieval-augmented",
            "token-optimization",
            "token-level",
            "machine-translation",
            "sentiment",
            "named-entity",
            "text-classification",
            "large-language-model",
            "llm-agent",
            "llm-emotion",
            "llm-decision",
            "llm-sysml",
            "dsm-llm",
            "chatgpt",
            "chat-gpt",
            "text-to-",
            "code-llm",
            "prompt-optimization",
            "prompt-injection",
            "autoregressive-",
            "tokenizer",
            "byte-modeling",
            "in-context-learning",
            "prefix-tuning",
            "parameter-efficient",
            "self-supervised-text",
            "text2sql",
            "rag-",
            "retrieval-augmented",
            "code2text",
            "sentiment-analysis",
            "text-mining",
            "code-generation",
            "codegen",
            "fact-checking",
            "natural-language",
            "neural-machine-translation",
            "masked-language",
            "pre-training",
            "semantic-parsing",
            "question-answering",
            "dialogue-system",
            "chatbot",
            "information-extraction",
            "textual-inversion",
            "textual-alignment",
            "concept-erasure",
        ],
        "nlp-llm",
    ),
    # === Multi-Agent & RL ===
    (
        [
            "multi-agent",
            "reinforcement-learning",
            "-rl-",
            "rl-",
            "game-theory",
            "swarm-",
            "multi-robot",
            "agent-",
            "-agent-",
            "agentic",
            "multi-task-rl",
            "deep-rl",
            "policy-gradient",
            "q-learning",
            "reinforce",
            "ppo-",
            "dqn-",
            "sac-",
            "td3",
            "reward-modeling",
            "reward-shaping",
            "inverse-reinforcement",
            "markov-decision",
            "mdp-",
            "meta-reinforcement",
            "meta-rl",
            "offline-rl",
            "online-rl",
            "multi-agent-control",
            "distributed-agent",
            "collaborative-agent",
            "multi-armed-bandit",
            "agent-memory",
            "agent-communication",
            "agent-coordination",
            "agent-orchestration",
            "agent-modeling",
            "agent-reasoning",
            "multi-agent-path",
            "multi-agent-consensus",
            "agent-collaboration",
            "agent-delegation",
            "cooperative-multi",
            "optimal-control-for-agent",
            "multi-agent-planning",
            "vector-policy",
            "routing-distraction",
            "agent-harness",
            "agent-first",
            "multi-agent-differential",
            "density-driven-multi-agent",
            "digital-twin-multi-agent",
            "multi-agent-clinical",
            "multi-agent-density",
            "delta-aware-multi-agent",
            "recursive-multi-agent",
        ],
        "multi-agent-rl",
    ),
    # === Signal Processing & Control ===
    (
        [
            "control-system",
            "-control-",
            "mpc-",
            "kalman-",
            "signal-processing",
            "filter-",
            "pid-",
            "dynamical-system",
            "system-identification",
            "observer-",
            "state-estimation",
            "disturbance-observer",
            "system-resilience",
            "uncertainty-mpc",
            "adaptive-control",
            "optimal-control",
            "robust-control",
            "predictive-control",
            "feedback-control",
            "nonlinear-control",
            "distributed-control",
            "safety-critical-control",
            "temporal-logic-control",
            "motion-control",
            "trajectory-control",
            "gain-control",
            "frequency-control",
            "fault-detection",
            "fault-diagnosis",
            "fault-tolerant-control",
            "cps-",
            "cps/",
            "cyber-physical",
            "iot-cps",
            "kuramoto-control",
            "networked-control",
            "event-triggered-control",
            "small-gain",
            "temporal-structural-fault",
            "admm-distributed",
            "nonlinear-mas",
            "plant-model-mismatch",
            "small-gain",
        ],
        "signal-control-systems",
    ),
    # === General ML ===
    (
        [
            "general-ml",
            "deep-learning",
            "machine-learning",
            "neural-network",
            "gradient-",
            "optimizer-",
            "regularization",
            "representation-learning",
            "self-supervised",
            "contrastive",
            "autoencoder",
            "vae-",
            "variational-autoencoder",
            "supervised-learning",
            "semi-supervised",
            "unsupervised-learning",
            "transfer-learning",
            "meta-learning",
            "few-shot",
            "zero-shot",
            "out-of-distribution",
            "ood-",
            "continual-learning",
            "lifelong-learning",
            "catastrophic-forgetting",
            "domain-adaptation",
            "domain-generalization",
            "model-merging",
            "model-fusion",
            "federated-learning",
            "ensemble-learning",
            "active-learning",
            "curriculum-learning",
            "imbalanced-learning",
            "noisy-label",
            "label-noise",
            "weakly-supervised",
            "knowledge-distillation",
            "distillation",
            "normalization",
            "batch-normalization",
            "attention-mechanism",
            "attention-",
            "regularization",
            "dropout",
            "loss-function",
            "loss-landscape",
            "hyperparameter",
            "architecture-search",
            "nas-",
            "neural-architecture",
            "model-compression",
            "model-pruning",
            "weight-sharing",
            "weight-init",
            "implicit-bias",
            "lottery-ticket",
            "wide-residual",
            "residual-network",
            "network-pruning",
            "sparsity",
            "mixture-of-experts",
            "moe-",
            "adversarial-training",
            "adversarial-defense",
            "causality",
            "causal-inference",
            "d-separation",
            "gaussian-process",
            "gp-",
            "random-feature",
            "kernel-method",
            "optimization-landscape",
            "loss-landscape",
            "neural-tangent",
            "ntk-",
            "flat-minima",
            "sharp-minima",
            "model-robustness",
            "robustness-",
            "dimpled-manifold",
            "mode-connectivity",
        ],
        "general-ml",
    ),
    # === AI Safety & Evaluation ===
    (
        [
            "ai-safety",
            "alignment-",
            "ai-alignment",
            "evaluation-benchmark",
            "ai-evaluation",
            "red-team",
            "jailbreak",
            "harmlessness",
            "bias-fairness",
            "ai-bias",
            "fairness-",
            "ai-ethics",
            "responsible-ai",
            "benchmark-",
            "eval-",
            "-benchmark",
            "ai-sycophancy",
            "ai-honesty",
            "ai-transparency",
            "explainability",
            "interpretability",
            "xai-",
            "ai-governance",
            "ai-regulation",
            "llm-safety",
            "model-evaluation",
            "robustness-benchmark",
            "ai-behavior-monitoring",
            "trustworthy",
            "trustworthiness",
            "ai-adapter-security",
            "trustworthy-qml",
            "specbench",
            "pac-bench",
            "saas-bench",
            "agentic-clear",
            "agentic-eval",
            "validation-driven",
            "ai-safety-assessment",
        ],
        "ai-safety-eval",
    ),
    # === Software Engineering ===
    (
        [
            "software-engineering",
            "devops-",
            "testing-",
            "code-tools",
            "git-",
            "ci-cd",
            "software-testing",
            "code-review",
            "monitoring-",
            "observability",
            "debugging-",
            "profiling",
            "software-architecture",
            "design-pattern",
            "code-analysis",
            "static-analysis",
            "api-design",
            "api-testing",
            "data-structure",
            "algorithm-design",
            "fullstack",
            "web-development",
            "microservice",
            "container",
            "docker",
            "kubernetes",
            "k8s",
            "node-",
            "typescript",
            "javascript",
            "electron-",
            "react-",
            "vue-",
            "database-design",
            "sql-optimization",
            "testing-framework",
            "integration-test",
            "unit-test",
            "code-quality",
            "agile-methodology",
        ],
        "software-engineering",
    ),
    # === Physics & Math ===
    (
        [
            "physics-",
            "-physics",
            "mathematical",
            "pde-",
            "differential-equation",
            "topology",
            "geometry",
            "statistical-physics",
            "statistical-mechanics",
            "complex-system",
            "nonlinear-dynamics",
            "chaos-",
            "chaotic",
            "random-matrix",
            "random-graph",
            "graph-theory",
            "combinatorics",
            "number-theory",
            "algebraic",
            "information-theory",
            "entropy",
            "stochastic-process",
            "stochastic-differential",
            "graph-",
            "network-science",
            "cellular-automata",
            "percolation",
            "phase-transition",
            "critical-phenomena",
            "fokker-planck",
            "langevin",
            "many-body-physics",
            "condensed-matter",
            "non-equilibrium",
            "non-equilibrium",
            "hermitian-",
            "non-hermitian",
            "topological-phase",
            "topological-order",
            "many-body-localization",
            "quantum-optical",
            "mathematical-morphology",
            "gauge-theory",
            "gauge-field",
            "fractal",
            "dynamical-systems",
            "ergodic",
            "kinetic-equation",
        ],
        "physics-math",
    ),
    # === Healthcare & Biomedical ===
    (
        [
            "healthcare",
            "biomedical",
            "bio-",
            "clinical-",
            "patient-",
            "disease-",
            "drug-discovery",
            "drug-target",
            "genomics",
            "proteomics",
            "metabolomics",
            "medical-imaging",
            "pathology",
            "cancer-",
            "tumor",
            "oncology",
            "cardiovascular",
            "cardiac",
            "hospital",
            "health-record",
            "ehr",
            "electronic-health",
            "neurodegenerative",
            "alzheimer",
            "parkinson",
            "epilepsy",
            "biomarker",
            "diagnosis",
            "pharmaco",
            "clinical-trial",
            "protein-",
            "dna-",
            "rna-",
            "single-cell",
            "sc-",
            "scrna",
            "gene-",
            "epigenetic",
            "immunology",
            "immune",
            "brain-tumor",
            "brain-lesion",
            "ett-",
            "tt-opd",
        ],
        "healthcare-bio",
    ),
    # === Data & Retrieval ===
    (
        [
            "data-retrieval",
            "search-",
            "information-retrieval",
            "database-",
            "query-",
            "index-",
            "rag-",
            "retrieval-augmented",
            "embedding-",
            "vector-database",
            "data-pipeline",
            "data-engineering",
            "data-quality",
            "data-cleaning",
            "data-integration",
            "data-warehouse",
            "etl-",
            "data-lake",
            "data-catalog",
            "data-lineage",
            "data-governance",
            "data-mesh",
            "recommender",
            "recommendation",
            "search-engine",
            "semantic-search",
            "elasticsarch",
            "solr",
            "feature-store",
            "feature-engineering",
            "data-augmentation",
            "data-synthesis",
            "news-search",
        ],
        "data-retrieval",
    ),
    # === Deployment & Optimization ===
    (
        [
            "deployment",
            "serving-",
            "mlops",
            "model-serving",
            "inference-serving",
            "edge-ai",
            "edge-deployment",
            "on-device",
            "mobile-ml",
            "quantization",
            "model-quantization",
            "pruning",
            "distillation",
            "model-compression",
            "efficient-inference",
            "model-optimization",
            "optimization-",
            "vllm",
            "tensorrt",
            "onnx",
            "openvino",
            "tflite",
            "coreml",
            "pipeline-parallel",
            "model-parallel",
            "distributed-training",
            "gpu-optimization",
            "cuda-",
            "power-profiling",
            "energy-efficient",
        ],
        "deployment-optimization",
    ),
    # === Security & Privacy ===
    (
        [
            "security-",
            "privacy-",
            "encryption",
            "cybersecurity",
            "adversarial-attack",
            "backdoor-",
            "poisoning",
            "differential-privacy",
            "dp-",
            "cryptography",
            "cryptographic",
            "homomorphic-encryption",
            "he-",
            "secure-computation",
            "secure-mpc",
            "federated-learning-security",
            "membership-inference",
            "model-inversion",
            "gradient-leakage",
            "side-channel",
            "timing-attack",
            "network-security",
            "intrusion-detection",
            "malware",
            "ransomware",
            "quantum-cryptography",
            "post-quantum-crypto",
            "zero-knowledge",
            "zkp",
            "access-control",
            "authentication",
            "vulnerability-detection",
            "data-anonymization",
            "uncloneable",
            "security-module",
            "discrete-signaling",
        ],
        "security-privacy",
    ),
    # === Knowledge Graph ===
    (
        [
            "knowledge-graph",
            "graph-neural",
            "gnn-",
            "ontology",
            "entity-linking",
            "kg-",
            "relationship-extraction",
            "graph-embedding",
            "graph-learning",
            "graph-classification",
            "graph-clustering",
            "graph-mining",
            "graph-algorithm",
            "graph-attention",
            "graph-transformer",
            "graph-convolution",
            "gcn",
            "graphsage",
            "graph-isomorphism",
            "heterogeneous-graph",
            "hgnn",
            "temporal-graph",
            "dynamic-graph",
            "graph-database",
            "neo4j",
            "knowledge-base",
            "knowledge-representation",
            "semantic-web",
            "rdf-",
            "sparql",
            "triplet-extraction",
        ],
        "knowledge-graph",
    ),
    # === Vision & Generative ===
    (
        [
            "vision-",
            "image-",
            "video-",
            "generative-",
            "gan-",
            "diffusion-",
            "stable-diffusion",
            "visual-",
            "cnn-",
            "vqa-",
            "caption-",
            "object-detection",
            "segmentation",
            "image-generation",
            "image-to-image",
            "video-generation",
            "video-understanding",
            "visual-question",
            "visual-reasoning",
            "visual-recognition",
            "image-classification",
            "image-retrieval",
            "image-segmentation",
            "face-recognition",
            "facial-",
            "pose-estimation",
            "action-recognition",
            "scene-understanding",
            "scene-graph",
            "optical-flow",
            "depth-estimation",
            "super-resolution",
            "image-restoration",
            "image-compression",
            "image-encoding",
            "visual-odometry",
            "slam-",
            "point-cloud",
            "3d-reconstruction",
            "style-transfer",
            "neural-style",
            "gaze-",
            "eye-tracking",
            "holographic",
            "neural-rendering",
            "multi-modal-vision",
            "multimodal-vision",
            "visual-search",
            "photoflow",
            "neuroflow",
            "clip-",
            "dalle",
            "point-e",
            "image-gpt",
            "glow-",
            "image-caption",
            "machine-vision",
        ],
        "vision-generative",
    ),
    # === Reasoning & Bayesian ===
    (
        [
            "bayesian-",
            "causal-",
            "causality",
            "probabilistic-",
            "uncertainty-",
            "monte-carlo",
            "mcmc",
            "variational-inference",
            "probabilistic-graphical",
            "bayesian-network",
            "bayesian-inference",
            "bayesian-optimization",
            "bayesian-neural",
            "gaussian-process",
            "gaussian-processes",
            "bayesian-deep",
            "bayesian-methods",
            "approximate-inference",
            "expectation-propagation",
            "belief-propagation",
            "markov-chain",
            "hidden-markov",
            "probabilistic-programming",
            "bayesian-model",
            "bayesian-nonparametric",
            "kalman-",
            "particle-filter",
            "state-space-model",
            "ssm-",
            "causal-discovery",
            "causal-effect",
            "counterfactual",
            "do-calculus",
            "structural-equation",
            "sem-",
            "reasoning-",
            "chain-of-thought",
            "abductive-reasoning",
        ],
        "reasoning-bayesian",
    ),
    # === Finance ===
    (
        [
            "finance",
            "portfolio",
            "market-",
            "trading",
            "stock-",
            "economic",
            "option-pricing",
            "risk-management",
            "risk-assessment",
            "hedging",
            "derivative",
            "financial-",
            "macroeconomic",
            "investor",
            "investment",
            "volatility",
            "correlation-matrix",
            "high-frequency-trading",
            "asset-pricing",
            "asset-allocation",
            "time-series-financial",
            "stock-analysis",
            "market-making",
            "market-informedness",
            "regime-adaptive",
            "portfolio-optimization",
            "portfolio-selection",
            "inverse-born-rule",
            "quantum-finance",
            "quantum-economic",
            "bbqram",
            "hotstart-quantum-portfolio",
            "market-microstructure",
        ],
        "finance",
    ),
    # === Tools & Frameworks ===
    (
        [
            "chrome-extension",
            "copilot-cli",
            "vscode-",
            "obsidian-",
            "web-to-obsidian",
            "skill-creator",
            "skill-extractor",
            "skill-rag",
            "dockerize",
            "research-api",
            "api-fallback",
            "research-skill",
            "frontend-best",
            "react-component",
            "skill-drift",
            "find-skills",
            "find-skill",
            "web-to-obsidian",
            "electron-typescript",
        ],
        "tools-frameworks",
    ),
]


def classify_by_name(skill_name):
    """Classify a skill based on its directory name using keyword rules."""
    name_lower = skill_name.lower().replace("_", "-")

    for keywords, category in CLASSIFICATION_RULES:
        for kw in keywords:
            if kw in name_lower:
                return category
    return None


def classify_skill(skill_name):
    """Classify a skill. Returns category name or 'other'."""
    result = classify_by_name(skill_name)
    if result:
        return result
    return "other"


def main():
    all_items = sorted(os.listdir(BASE))

    # Get truly flat skills (not already in a category dir)
    flat_skills = []
    for item in all_items:
        if item in NON_SKILL:
            continue
        item_path = os.path.join(str(BASE), item)
        if not os.path.isdir(item_path):
            continue
        # Skip known category directories
        if item in CATEGORY_DIRS:
            continue
        # Check if it has sub-dirs (meaning it's already categorized)
        subdirs = [
            x
            for x in os.listdir(item_path)
            if os.path.isdir(os.path.join(item_path, x))
            and x not in ("references", "assets", "scripts", "templates")
        ]
        if len(subdirs) >= 3:
            continue  # It's a category dir itself
        flat_skills.append(item)

    print(f"Flat skills to classify: {len(flat_skills)}")

    # Classify each
    classified = defaultdict(list)
    unclassified = []

    for skill in flat_skills:
        cat = classify_skill(skill)
        classified[cat].append(skill)
        if cat == "other":
            unclassified.append(skill)

    print("\n=== Classification Results ===")
    total = 0
    for cat, skills in sorted(classified.items(), key=lambda x: -len(x[1])):
        print(f"  {cat}: {len(skills)} skills")
        total += len(skills)
    print(f"  Total: {total}")

    print("\n=== Unclassified ('other') ===")
    for s in unclassified:
        print(f"  {s}")

    # Now move them
    print("\n=== Moving skills to category directories ===")
    moves = 0
    errors = 0

    for cat, skills in classified.items():
        cat_path = os.path.join(str(BASE), cat)
        os.makedirs(cat_path, exist_ok=True)

        for skill in skills:
            _ = os.path.join(BASE, skill)
            dst = os.path.join(cat_path, skill)

            if os.path.exists(dst):
                print(f"  SKIP (exists): {skill} -> {cat}/{skill}")
                errors += 1
                continue

            # Use git mv for proper tracking
            rel_src = f"collection/skills/{skill}"
            rel_dst = f"collection/skills/{cat}/{skill}"

            result = subprocess.run(
                ["git", "mv", rel_src, rel_dst],
                cwd="/Users/hiyenwong/projects/ai_projects/ai_collection",
                capture_output=True,
                text=True,
            )

            if result.returncode == 0:
                moves += 1
                if moves % 100 == 0:
                    print(f"  Progress: {moves} moved...")
            else:
                print(f"  ERROR moving {skill}: {result.stderr.strip()}")
                errors += 1

    print(f"\nDone: {moves} skills moved, {errors} errors")


if __name__ == "__main__":
    main()
