#!/usr/bin/env python3
"""Classify flat skills into category subdirectories based on name keywords.

A "flat skill" is a directory directly under collection/skills/ that contains
a SKILL.md file.  Directories that do NOT contain SKILL.md are treated as
category containers and skipped.
"""

import os
import sys
import subprocess
from collections import defaultdict
from pathlib import Path

BASE = Path(__file__).resolve().parent.parent / "collection" / "skills"
REPO_ROOT = Path(__file__).resolve().parent.parent

# Category directories to exclude from classification
CATEGORY_DIRS = {
    'agent-tools', 'ai-ml', 'ai-safety-eval', 'chat-history-lancedb',
    'continual-learning', 'control-systems', 'data-retrieval',
    'deployment-optimization', 'finance', 'general-ml', 'healthcare-bio',
    'knowledge-graph', 'math-statistics', 'medical', 'memory',
    'multi-agent-rl', 'neuroscience', 'nlp-llm', 'other', 'physics-math',
    'quantum', 'reasoning-bayesian', 'reinforcement-learning',
    'security-privacy', 'signal-control-systems', 'skill-rag-indexer',
    'software-engineering', 'spiking-neuromorphic', 'systems-engineering',
    'tools-frameworks', 'vision-generative',
}

# Non-skill files
NON_SKILL = {'README.md', 'SKILL.md', '_INDEX.json', 'INDEX.md', 'DESCRIPTION.md', 'assets', 'references', 'scripts'}

# Keyword-based classification rules: (keywords, category)
# Ordered by specificity - first match wins
CLASSIFICATION_RULES = [
    # === Neuroscience ===
    (['brain', 'neural', 'neuro', 'cortex', 'cortical', 'cortico',
      'eeg', 'fmri', 'meg', 'ecog', 'ieeg', 'seeg',
      'bci', 'spiking', 'spike', 'synaptic', 'synapse', 'synapt',
      'hippocamp', 'cerebellar', 'thalam',
      'connectome', 'connectivity', 'connectiv',
      'neuron', 'neurons',
      'attractor', 'oscillat', 'plasticity', 'plastic',
      'cognit', 'memory', 'perception', 'percept',
      'attention', 'sensory', 'sensorimotor',
      'motor-cortex', 'motor-imagery', 'motor-primitives',
      'olfactory', 'visual-cortex', 'auditory',
      'prefrontal', 'somatosensory',
      'resting-state', 'bold-signal',
      'neural-field', 'neural-mass', 'neural-code',
      'neural-transfer', 'neural-variability', 'neural-emulator',
      'neural-lyapunov', 'neural-operator', 'neural-ode',
      'neuromodulation', 'neurosteroid',
      'tms', 'tdcs', 'stimulation', 'stimul',
      'intracranial', 'multisensory',
      'cognition',
      'alzheimer', 'parkinson', 'epilepsy', 'dementia', 'seizure',
      'behavioral', 'behavioural', 'psychosis', 'psychiatric',
      'sleep', 'dream', 'consolidation',
      'neurogenesis', 'neurodevelopmental', 'neurodegenerat',
      'consciousness', 'metacognitive', 'meta-cognitive',
      'mind', 'engram', 'cann', 'attractor-network',
      'dendritic', 'dendrite', 'axon',
      'glioblastoma', 'rodent', 'zebrafish',
      'retina', 'retinomorphic', 'photoreceptor',
      'neuroscience', 'neuroai', 'neurocybernetic',
      'neurobiolog', 'neuromimetic',
      'reservoir', 'reservoir-computing',
      'rnn', 'recurrent', 'lstm', 'gru',
      'hopfield', 'boltzmann',
      'predictive-coding', 'predictive-feedback',
      'ei-balance', 'ei-network', 'ei-dynamics',
      'winner-take-all', 'wta',
      'memristor', 'memristive',
      'neuromorphic', 'neurocomputation',
      'lif-neuron', 'qif-neuron',
      'biological', 'biologically', 'bio-inspired',
      'neuro-inspired', 'neuro-grounded',
      'tribe-v2', 'tribev2', 'beast3d',
      'whisper-ecog',
      'tinnitus', 'stress', 'fatigue',
      'emotion', 'affective',
      'autism', 'adhd', 'abide',
      'fmri-foundation', 'eeg-foundation', 'meg-foundation',
      'brain-dit', 'braindinobrain',
      'spikingbrain', 'neurostorm', 'neurotrain',
      'neuroring', 'neurobiological',
      'neuroplastic',
      'spikingjelly', 'spikingmoe',
      'cognitive-flexibility', 'cognitive-load',
      'cognitive-model', 'cognitive-network',
      'cognitive-state', 'cognitive-fatigue',
      'neurrate', 'neurrator',
      'emomind', 'affective-brain',
      'mesoscale-brain', 'gyralnet',
      'platonic-representations-brain',
      'brain-inspired', 'brain-digital',
      'brain-data', 'brain-foundation',
      'brain-higher', 'brain-mri',
      'brain-of', 'brain-omni',
      'brain-oscillation', 'brain-to',
      'brainfuse', 'brainstorming',
      'eyebrain', 'pupil',
      'photobiomodulation',
      'locomot', 'gaze',
      'depression', 'anxiety',
      'meditation',
      'mouse', 'mice',
      'visual',
      'vestibular',
      'circuit',
      'population',
      'dynamics',
      'coupled', 'coupling', 'synchron', 'rhythm',
      'critical', 'scaling-law', 'scaling-laws',
      'representation', 'embedding', 'trajectory',
      'receptor', 'cell',
      'organism',
      'digital-twin',
      'neural-set', 'neural-brain',
      'neural-critical', 'neural-phase',
      'neuralset',
      'neuro-sparse', 'neuro-dendritic',
      'neuro-rate',
      'neuro-adapter',
      'neuro-transfer-unification',
      'neural-transfer-unification',
      'neuro-ai',
      'schrodinger',
      'kuramoto',
      'stuart-landau',
      'thermodynamic-networks',
      'mean-field',
      'field-theory',
      'self-organizing', 'self-organising',
      'self-evolving',
      'world-model', 'worldkv',
      'mental',
      'free-energy', 'energy-based',
      'fano', 'poisson',
      'nonlinear-rnn', 'low-rank-rnn', 'low-rank-gluing',
      'fixed-point', 'compositionality',
      'von-econom',
      'lfp',
      'dti', 'tractography',
      'tus', 'cmut', 'ultrasound',
      'nerve', 'ganglion',
      'senso',
      'bno', 'brain-neural-operator',
      'tau-bno',
      'realm-lfp',
      'snnf',
      'spatiotemporal-tdann',
      'strand-survival',
      'ultrastructure',
      'variance-brain',
      'verievol',
      'visae',
      'weighted-brain',
      'working-memory',
      'zenbrain',
      'zeroth-order',
      'psi-shared', 'shared-state',
      'funessian',
      'geodynamics', 'geometric-mean-field',
      'hot-state',
      'infinite-horizon',
      'inhibitory-neuristor',
      'kinetic-energy',
      'lattice-field',
      'layer-codes',
      'level-crossing',
      'local-cycles',
      'magnet-brain',
      'many-body-super',
      'mixed-potential',
      'modal-neural',
      'moire',
      'moving-mri',
      'mt-direction',
      'network-aware',
      'neural-brain',
      'neural-code',
      'neural-critical',
      'neural-decoder',
      'neural-digital',
      'noise-field',
      'ode-complexity',
      'partial-annealing',
      'path-integral',
      'pulse-level',
      'quantized-return',
      'quasilinear',
      'qubridge',
      'random-riemann',
      'scaling-optimal',
      'score-broadcast',
      'secretary-problem',
      'self-organized', 'self-orthogonalizing',
      'self-sustained',
      'semi-device',
      'sensing-intelligence',
      'sheaf',
      'shia-sysml',
      'singular-value',
      'sparse-mamba',
      'sparse-temporal',
      'split-primes',
      'staged-training',
      'state-adaptive',
      'stochastic-synaptic',
      'stochastic-momentum',
      'stochastic-resonance',
      'structured-light',
      'superconducting-neuron',
      'suprasnn',
      'surface-code',
      'svp-lattice',
      'symmetry-protected',
      'synaptic-weight',
      'synaptic-matrix',
      'synaptic-motif',
      'synchronization',
      'syndrome-resampling',
      'synthetic-biological',
      'system-dse',
      'taiyi-jinhua',
      'tea-nets',
      'temporal-ecological',
      'think-aloud',
      'topo-omni',
      'traced-activation',
      'transcranial',
      'unified-neural',
      'universal-object',
      'untrained-cnn',
      'updated-neuron',
      'v1-digital',
      'vector-space',
      'warmstart',
      'weighted-partitions',
      'yb-photonic',
      'non-hermitian',
      'open-quantum',
      'operator-observable',
      'optimal-shadow',
      'extension-profile',
      'biomysterybench',
      'liquid-tad', 'liquidtad',
      'motif-based',
      'mtt-bench',
      'multilevel-interactive',
      'multi-view-o',
      'multiview-information',
      'nanophotonet',
      'native-active',
      'naturalistic',
      'nh-gcat',
      'noise-induced',
      'normalizing-trajectory',
      'online-generalised',
      'parrsb-exascale',
      'perception-neuroscience',
      'physical-foundation',
      'plastic-arbor',
      'predictive-coding',
      'predictive-feedback',
      'predictive-subspace',
      'prospective-coding',
      'sensation-modulating',
      'sensorless-gaze',
      'signal-transform',
      'slow-rhythms',
      'snr-sample',
      'stimulus-symmetries',
      'stm-sequence',
      'structural-plasticity',
      'stuart-landau',
      'successor-representations',
      'sumo-whole',
      'synthetic-biological',
      'taiyi-jinhua',
      'tea-nets',
      'temporal-ecological',
      'thermodynamic-networks',
      'think-aloud',
      'topo-omni',
      'traced-activation',
      'transcranial',
      'unified-neural',
      'universal-object',
      'untrained-cnn',
      'updated-neuron',
      'v1-digital',
      'vector-space',
      'von-econom',
      'working-memory',
      'worldkv',
      'zenbrain',
      'zeroth-order',
      'neurobridge',
      'neurocybernetic',
      'neuromechanical',
      'neuromimetic',
      'neuromodulated',
      'neuroplastic',
      'neuroscience-frontiers',
      'neuroring',
      'neurobiological',
      'neuroai',
      'omnimouse',
      'openmrf',
      'smartvector',
    ], 'neuroscience'),

    # === Quantum ===
    (['quantum', 'qubit', 'qec', 'qaoa', 'qpe', 'vqe',
      'clifford', 'entanglement', 'qldpc', 'superconducting',
      'trapped-ion', 'qml', 'qcnn', 'qnn', 'qgan',
      'tensor-network',
      'pauli', 'hamiltonian', 'lindblad', 'bloch',
      'bosonic', 'gkp', 'rydberg', 'fluxonium', 'transmon',
      'qkd', 'qubo', 'qfi', 'qem', 'qrc',
      'iqp', 'vqpu', 'qcn', 'qcmi',
      'falqon', 'photon-heralded', 'photonic-qml',
      'lattice-surgery', 'surface-code',
      'stabilizer', 'nonstabilizerness',
      'topological-quantum', 'topological-subsystem',
      'fermionic', 'fermion',
      'anyon', 'non-abelian',
      'qutrit', 'qudit',
      'qkd-routing', 'qkd-extractors',
      'self-sifting-qkd',
      'module-lattice-security', 'pqc',
      'post-quantum',
      'lwe', 'nwe', 'cryptanalysis',
      'nonlocality', 'bell-test',
      'steerability', 'nonlocal',
      'cat-state', 'ghz', 'dicke-state',
      'shor', 'grover', 'qft', 'iqft',
      'vqc', 'qbla',
      'calderbank', 'steane',
      'ldpc', 'qec-decoder', 'qec-formal',
      'syndrome', 'syndrome-decoding',
      'error-correction', 'error-mitigation',
      'pauli-propagation',
      'gibbs-state', 'density-matrix',
      'coherent-state', 'squeezed-state',
      'measurement-based',
      'post-selected', 'weak-measurement',
      'photonic-variational', 'photonic-deep',
      'deep-photonic', 'deep-binarized-photonic',
      ' scalable-photonic', 'parametric-oscillator',
      'analog-quantum', 'analog-neuromorphic',
      'alternating-minimization-gate',
      'affine-subcode', 'logical-catalyst',
      'lottery-bp', 'sparse-mamba-decoder-qec',
      'two-branch-css', 'coset-ensemble',
      'css-syndrome', 'qec-rademacher',
      'non-hermitian-quantum', 'open-quantum',
      'quasilinear-equivalence', 'qubridge',
      'differentiable-spin', 'dicke-state-ansatz',
      'gated-qkan', 'optimal-ansatz',
      'sample-optimal-gaussian', 'scaling-optimal-channel',
      'optimal-shadow', 'semi-device',
      'permutation-asymmetry-bell',
      'kvant', 'qrc',
    ], 'quantum'),

    # === Spiking & Neuromorphic ===
    (['spiking', 'snn', 'neuromorphic',
      'snngp', 'spike-timing', 'stdp',
      'event-driven', 'spike-driven',
      'pcnn', 'spike-image', 'spike-nvpt',
      'lateral-inhibition', 'snn-acceleration',
      'clane-neuromorphic', 'xoresnet',
      'neuro-burst', 'temporal-coding',
      'unispike', 'vencircuit', 'ven-circuit',
      'transport-mean-field-snn',
      'globally-optimal-snn',
      'clockless-neuromorphic',
      'event2vec', 'ecram',
      'sram-cim', 'neuroring',
      'spiker', 'suprasnn',
      'edgespike', 'erecon',
      'clp-snn', 'elsa-snn',
      'sharpness-aware-surrogate-snn',
      'sealkd-snn', 'stars-snn',
      'cognisnn', 'snn-fairness',
      'snn-firing', 'snn-internal',
      'snn-learning', 'snn-low',
      'snn-mcu', 'snn-microcontroller',
      'snn-mlir', 'snn-near',
      'snn-performance', 'snn-quantized',
      'snn-rademacher', 'snn-sequence',
      'snn-universal', 'snn-working',
      'snr-sample', 'snnf',
      'spikingbandpass', 'spiking-compositional',
      'spiking-computational', 'spiking-ep',
      'spiking-event', 'spiking-free',
      'spiking-memristor', 'spiking-mllm',
      'spiking-mode', 'spiking-neural',
      'spiking-oscillation', 'spiking-phase',
      'spiking-quantum', 'spiking-recurrent',
      'spiking-reservoir', 'spiking-rl',
      'spiking-sequence', 'spiking-temporal',
      'spiking-tolman', 'spiking-transformer',
      'spikingbrain', 'spikingjelly',
      'spikingmoe', 'spikereg',
      'spiker-ll', 'spike-agreement',
      'spike-forecast', 'spike-image',
      'spike-mllm', 'spike-nvpt',
      'spike-ptsd', 'spike-sparsity',
      'spike-timing',
      'spike-driven-large',
      'structured-recurrent-snn',
      'sub-bit-snn', 'surrogate-gradient-snn',
      'three-factor-snn',
      'qb-lif', 'qlif',
      'shiftlif', 'unispike',
      'lif-neuron', 'if-neuron',
      'spiking-transformer-effective',
      'snn-fpga', 'snn-data',
    ], 'spiking-neuromorphic'),

    # === NLP & LLM ===
    (['llm', 'language-model', 'transformer',
      'gpt', 'bert', 'nlp',
      'text-generation', 'prompt',
      'rag', 'retrieval-augmented',
      'token', 'machine-translation', 'sentiment',
      'named-entity', 'text-classification',
      'chatgpt', 'chat-gpt',
      'text-to', 'code-llm',
      'autoregressive', 'tokenizer',
      'byte-modeling', 'in-context-learning',
      'prefix-tuning', 'parameter-efficient',
      'text2sql', 'code2text',
      'text-mining', 'code-generation', 'codegen',
      'fact-checking', 'natural-language',
      'neural-machine-translation',
      'masked-language', 'pre-training',
      'semantic-parsing', 'question-answering',
      'dialogue', 'chatbot',
      'information-extraction',
      'textual', 'concept-erasure',
      'blockrank', 'incontext',
      'symboliclight', 'wta-spiking-transformer',
      'spike-driven-large-language',
      'bispikclm', 'bleg-llm',
      'brain-guided-llm', 'brain-llm',
      'sleep-like-consolidation-llm',
      'dsm-llm', 'spike-driven-large',
      'llm-wiki',
    ], 'nlp-llm'),

    # === Multi-Agent & RL ===
    (['multi-agent', 'reinforcement-learning',
      'rl-', '-rl', 'game-theory',
      'swarm', 'multi-robot',
      'agent', 'agentic',
      'multi-task-rl', 'deep-rl',
      'policy-gradient', 'q-learning',
      'ppo', 'dqn', 'sac', 'td3',
      'reward', 'inverse-reinforcement',
      'markov', 'mdp',
      'meta-reinforcement', 'meta-rl',
      'offline-rl', 'online-rl',
      'multi-agent-control', 'distributed-agent',
      'collaborative', 'multi-armed',
      'agent-memory', 'agent-communication',
      'agent-coordination', 'agent-orchestration',
      'agent-modeling', 'agent-reasoning',
      'multi-agent-path', 'multi-agent-consensus',
      'cooperative', 'optimal-control-for-agent',
      'vector-policy', 'routing-distraction',
      'agent-harness', 'agent-first',
      'byzantine', 'consensus',
      'digital-twin-multi-agent',
      'delta-aware', 'recursive-multi',
      'density-driven-multi',
      'anai-autonomous', 'autopoiesis',
      'self-evolving', 'socratic-swe',
      'espl', 'evotrace',
      'gaussian-grpo', 'drpo',
      'scalelogic-rl', 'stepo',
      'grpo',
    ], 'multi-agent-rl'),

    # === Signal Processing & Control ===
    (['control-system', 'control', 'mpc', 'kalman',
      'signal-processing', 'filter',
      'pid', 'dynamical-system',
      'system-identification', 'observer',
      'state-estimation', 'disturbance',
      'system-resilience', 'resilien',
      'adaptive-control', 'optimal-control',
      'robust-control', 'predictive-control',
      'feedback', 'nonlinear-control',
      'distributed-control', 'safety-critical',
      'temporal-logic', 'motion-control',
      'trajectory', 'gain-control',
      'fault-detection', 'fault-diagnosis',
      'fault-tolerant', 'cps',
      'cyber-physical', 'iot-cps',
      'kuramoto-control', 'networked-control',
      'event-triggered', 'small-gain',
      'admm', 'nonlinear-mas',
      'plant-model', 'amortized-nonlinear-mpc',
      'bandwidth-reduction', 'buildyn',
      'convex-hybrid', 'constraint',
      'data-driven-reachability',
      'decentralized', 'differential-transformer',
      'discrete-signaling', 'dual-envelope',
      'energy-regularized', 'game-theoretic',
      'heterogeneous-contract', 'infinite-horizon',
      'invariant', 'linear-quadratic',
      'lyapunov', 'model-predictive',
      'nonlinear-separation', 'passivity',
      'resilient-output', 'singularity-free',
      'stein-variational', 'stochastic',
      'uncertainty', 'bandwidth',
    ], 'signal-control-systems'),

    # === General ML ===
    (['general-ml', 'deep-learning', 'machine-learning',
      'neural-network', 'gradient', 'optimizer',
      'regularization', 'representation-learning',
      'self-supervised', 'contrastive',
      'autoencoder', 'variational-autoencoder',
      'supervised', 'semi-supervised',
      'unsupervised', 'transfer-learning',
      'meta-learning', 'few-shot', 'zero-shot',
      'out-of-distribution', 'ood',
      'continual-learning', 'lifelong',
      'catastrophic', 'domain-adaptation',
      'domain-generalization',
      'model-merging', 'model-fusion',
      'federated', 'ensemble',
      'active-learning', 'curriculum',
      'imbalanced', 'noisy-label',
      'label-noise', 'weakly',
      'knowledge-distillation', 'distillation',
      'normalization', 'batch-normalization',
      'attention-mechanism',
      'dropout', 'loss-function', 'loss-landscape',
      'hyperparameter', 'architecture-search',
      'neural-architecture', 'nas',
      'model-compression', 'model-pruning',
      'weight', 'implicit-bias', 'lottery',
      'residual', 'network-pruning', 'sparsity',
      'mixture-of-experts', 'moe',
      'adversarial', 'causality', 'causal',
      'gaussian-process',
      'kernel-method', 'optimization-landscape',
      'neural-tangent', 'ntk',
      'flat-minima', 'sharp-minima',
      'model-robustness', 'robustness',
      'dimpled', 'mode-connectivity',
      'fade-adaptive', 'early-stopping',
      'confidence-dynamics', 'double-preconditioning',
      'hebbian', 'margin-runtime',
      'unipool', 'sae-optimality',
      'sparseforge', 'stability-goal',
      'persona-pruner', 'rollout-adaptive',
      'characterize-then-distill', 'dart-adaptive',
      'darwin-family', 'espl',
      'evotrace', 'hes-data',
      'ml-complexity', 'representation-use',
      'srf-similarity', 'suco-sufficiency',
      'detecting-reducing', 'declarative-self',
      'democratic-icai', 'iceberg-error',
      'kat-kl', 'readiness-driven',
      'how-we-monitor', 'ice-review',
      'self-challenge', 'self-verification',
      'antbrain', 'cmos',
      'xor', 'digit',
      'reconfigurable', 'descript',
      'learning-developmental',
      'learning-dynamic-stability',
      'effective-plasticity', 'effective-rank',
      'effective-target', 'adaptivity',
      'analog', 'geno',
      'geodynamics', 'hypergeometric',
      'intrinsic', 'jeffreys',
      'jost-function', 'lionmuon',
      'loewner', 'magic-number',
      'majority-of', 'majorization',
      'naturality', 'noise-field',
      'normalizing', 'pavement',
      'relaxation', 'successor',
      'super-factory', 'teaching',
      'tscg', 'vibe',
      'tunneling-phase', 'universal',
    ], 'general-ml'),

    # === AI Safety & Evaluation ===
    (['ai-safety', 'alignment',
      'evaluation-benchmark', 'ai-evaluation',
      'red-team', 'jailbreak', 'harmlessness',
      'bias-fairness', 'ai-bias', 'fairness',
      'ai-ethics', 'responsible-ai',
      'benchmark', 'eval',
      'ai-sycophancy', 'ai-honesty',
      'ai-transparency', 'explainability',
      'interpretability', 'xai',
      'ai-governance', 'ai-regulation',
      'llm-safety', 'model-evaluation',
      'robustness-benchmark',
      'trustworthy', 'trustworthiness',
      'specbench', 'pac-bench',
      'saas-bench', 'agentic-clear',
      'agentic-eval', 'validation-driven',
      'ai-safety-assessment',
      'iit-critical', 'iit-fep',
      'glasswing', 'project-glasswing',
      'project-deal', 'project-fetch',
      'project-vend', 'stability-goal-obfuscation',
      'glasswing-vulnerability',
    ], 'ai-safety-eval'),

    # === Software Engineering ===
    (['software-engineering', 'devops',
      'testing', 'code-tools', 'git-',
      'ci-cd', 'code-review',
      'monitoring', 'observability',
      'debugging', 'profiling',
      'software-architecture', 'design-pattern',
      'code-analysis', 'static-analysis',
      'api-design', 'api-testing',
      'data-structure', 'algorithm-design',
      'fullstack', 'web-development',
      'microservice', 'container', 'docker',
      'kubernetes', 'k8s',
      'typescript', 'javascript',
      'electron', 'react', 'vue',
      'database', 'sql',
      'integration-test', 'unit-test',
      'code-quality', 'agile',
      'codex-session', 'coding-agents',
      'modern-systems-engineering',
      'systems-engineering', 'sheaf-consistency',
      'shia-sysml', 'experiment-as-code',
      'readiness-driven-pipeline',
      'tscg-tool-schema',
    ], 'software-engineering'),

    # === Physics & Math ===
    (['physics', 'mathematical',
      'pde', 'differential-equation',
      'topology', 'geometry',
      'statistical-physics', 'statistical-mechanics',
      'complex-system', 'nonlinear-dynamics',
      'chaos', 'chaotic',
      'random-matrix', 'random-graph',
      'graph-theory', 'combinatorics',
      'number-theory', 'algebraic',
      'information-theory', 'entropy',
      'stochastic', 'graph-',
      'network-science', 'cellular-automata',
      'percolation', 'phase-transition',
      'critical-phenomena',
      'fokker-planck', 'langevin',
      'many-body', 'condensed-matter',
      'non-equilibrium',
      'hermitian', 'non-hermitian',
      'topological-phase', 'topological-order',
      'many-body-localization',
      'gauge-theory', 'fractal',
      'ergodic', 'kinetic',
      'tensor', 'matrix', 'linear-algebra',
      'probability', 'bayesian',
      'statistics', 'optimization',
      'numerical', 'ode',
      'families-linear', 'brody-exponent',
      'arfima', 'degree-tensor',
      'discrete-heat', 'extension-profile',
      'gamma-c', 'graphical-coaction',
      'gravitational', 'hypergeometric',
      'infinite-horizon', 'jeffreys',
      'jost-function', 'krylov',
      'level-crossing', 'lionmuon',
      'loewner', 'magic-number',
      'majority-of', 'majorization',
      'many-body-super', 'mersenne',
      'modular-forms', 'modular-nahm',
      'mole-lambda', 'naturality',
      'prime-cohomological', 'random-riemann',
      'secretary-problem', 'split-primes',
      'svp-lattice', 'weighted-partitions',
      'algorithmic-bohmian',
    ], 'physics-math'),

    # === Healthcare & Biomedical ===
    (['healthcare', 'biomedical', 'bio-',
      'clinical', 'patient', 'disease',
      'drug', 'genomics', 'proteomics',
      'medical-imaging', 'pathology',
      'cancer', 'tumor', 'oncology',
      'cardiovascular', 'cardiac',
      'hospital', 'health-record', 'ehr',
      'pharmaco', 'clinical-trial',
      'protein', 'dna', 'rna',
      'single-cell', 'gene',
      'epigenetic', 'immunology', 'immune',
      'fqpdr-medical', 'pinns-medical',
      'hybrid-intelligent-mental',
      'adaptive-hybrid-feature-fusion-medical',
      'medical',
    ], 'healthcare-bio'),

    # === Data & Retrieval ===
    (['data-retrieval', 'search-',
      'information-retrieval', 'database',
      'query', 'index-',
      'embedding', 'vector-database',
      'data-pipeline', 'data-engineering',
      'data-quality', 'data-cleaning',
      'recommender', 'recommendation',
      'search-engine', 'semantic-search',
      'feature-store', 'feature-engineering',
      'data-augmentation', 'news-search',
      'consulting-report',
    ], 'data-retrieval'),

    # === Deployment & Optimization ===
    (['deployment', 'serving', 'mlops',
      'model-serving', 'inference-serving',
      'edge-ai', 'edge-deployment',
      'quantization', 'pruning',
      'model-compression', 'efficient-inference',
      'model-optimization',
      'vllm', 'tensorrt', 'onnx',
      'openvino', 'tflite', 'coreml',
      'pipeline-parallel', 'model-parallel',
      'distributed-training',
      'gpu', 'cuda', 'power-profiling',
      'energy-efficient',
    ], 'deployment-optimization'),

    # === Security & Privacy ===
    (['security', 'privacy', 'encryption',
      'cybersecurity', 'adversarial-attack',
      'backdoor', 'poisoning',
      'differential-privacy',
      'cryptography', 'cryptographic',
      'homomorphic', 'secure-computation',
      'membership-inference',
      'side-channel', 'timing-attack',
      'network-security', 'intrusion',
      'malware', 'ransomware',
      'zero-knowledge',
      'access-control', 'authentication',
      'vulnerability',
      'cross-layer-crypto', 'crypto-agility',
      'module-lattice-security', 'pqc',
      'post-quantum', 'lwe',
      'hybrid-pqc', 'disaggregate-secure',
    ], 'security-privacy'),

    # === Knowledge Graph ===
    (['knowledge-graph', 'graph-neural', 'gnn',
      'ontology', 'entity-linking',
      'kg-', 'relationship',
      'graph-embedding', 'graph-learning',
      'graph-classification', 'graph-clustering',
      'graph-attention', 'graph-transformer',
      'graph-convolution', 'gcn',
      'heterogeneous-graph', 'hgnn',
      'temporal-graph', 'dynamic-graph',
      'graph-database',
      'knowledge-base', 'knowledge-representation',
      'semantic-web', 'rdf', 'sparql',
      'drl-gnn', 'federated-brain',
      'gnn-',
    ], 'knowledge-graph'),

    # === Vision & Generative ===
    (['vision', 'image', 'video', 'generative',
      'gan', 'diffusion', 'stable-diffusion',
      'visual', 'cnn', 'vqa', 'caption',
      'object-detection', 'segmentation',
      'image-generation', 'image-to-image',
      'video-generation', 'video-understanding',
      'visual-question', 'visual-reasoning',
      'visual-recognition', 'image-classification',
      'image-retrieval', 'image-segmentation',
      'face', 'pose-estimation', 'action-recognition',
      'scene', 'optical-flow', 'depth',
      'super-resolution', 'image-restoration',
      'image-compression', 'slam',
      'point-cloud', '3d-reconstruction',
      'style-transfer', 'neural-style',
      'holographic', 'neural-rendering',
      'multi-modal-vision', 'multimodal-vision',
      'visual-search',
      'photoflow', 'clip',
      'face-perception', 'coarse-feedback',
    ], 'vision-generative'),

    # === Reasoning & Bayesian ===
    (['bayesian', 'causal', 'causality',
      'probabilistic', 'uncertainty',
      'monte-carlo', 'mcmc', 'variational-inference',
      'bayesian-network', 'bayesian-inference',
      'bayesian-optimization', 'bayesian-neural',
      'gaussian-process',
      'belief-propagation', 'message-passing',
      'markov', 'hidden-markov',
      'kalman', 'particle-filter',
      'state-space', 'ssm',
      'causal-discovery', 'counterfactual',
      'reasoning', 'chain-of-thought',
      'abductive',
      'exponential-family-predictive',
      'closed-form-predictive',
    ], 'reasoning-bayesian'),

    # === Finance ===
    (['finance', 'portfolio', 'market',
      'trading', 'stock', 'economic',
      'option-pricing', 'risk-management',
      'hedging', 'derivative',
      'financial', 'macroeconomic',
      'investor', 'investment',
      'volatility', 'high-frequency',
      'asset-pricing', 'asset-allocation',
      'akshare', 'thsdk',
      'prediction-markets', 'path-integral-default',
      'markets-hard', 'warmstart-dl',
    ], 'finance'),

    # === Tools & Frameworks ===
    (['chrome-extension', 'copilot-cli',
      'obsidian', 'web-to-obsidian',
      'skill-creator', 'skill-extractor',
      'skill-rag', 'dockerize',
      'research-api', 'api-fallback',
      'research-skill', 'frontend-best',
      'react-component', 'skill-drift',
      'find-skills', 'find-skill',
      'electron-typescript',
      'claude-code', 'opencode', 'openspec',
      'cursor-rules', 'codex-session',
      'dogfood', 'autoresearch',
      'teach-cofounder', 'super-factory',
      'iamb-matrix', 'vibe-calibration',
      'vocabulary-extension',
      'yuanbao', 'tscg-tool',
      'accessibility-wcag',
      'anthropic-founder', 'anthropic-institute',
      'anthropic-interviewer',
      'mckinsey', 'tech-exposure',
      '2028-ai', '81k-ai',
      'ai-complex-networks', 'ai-math-discovery',
      'ai-scientific-workflow',
      'paving-way-agents',
      'analog-interaction',
      'karma-economy',
      'readiness-driven-pipeline',
    ], 'tools-frameworks'),
]


def classify_by_name(skill_name):
    """Classify a skill based on its directory name using keyword rules."""
    name_lower = skill_name.lower().replace('_', '-')

    for keywords, category in CLASSIFICATION_RULES:
        for kw in keywords:
            if kw in name_lower:
                return category
    return None


def classify_skill(skill_name):
    """Classify a skill. Returns category name or 'other'."""
    result = classify_by_name(skill_name)
    if result:
        return result
    return 'other'


def main():
    all_items = sorted(os.listdir(BASE))

    # Get truly flat skills: a directory that contains SKILL.md.
    # Directories WITHOUT SKILL.md are category containers and are skipped.
    flat_skills = []
    for item in all_items:
        if item in NON_SKILL:
            continue
        item_path = os.path.join(str(BASE), item)
        if not os.path.isdir(item_path):
            continue
        # Skip known category directories
        if item in CATEGORY_DIRS:
            continue
        # A flat skill must contain SKILL.md at its root
        if not os.path.isfile(os.path.join(item_path, "SKILL.md")):
            continue  # category container or non-skill dir
        flat_skills.append(item)

    print(f"Flat skills to classify: {len(flat_skills)}")

    # Classify each
    classified = defaultdict(list)
    unclassified = []

    for skill in flat_skills:
        cat = classify_skill(skill)
        classified[cat].append(skill)
        if cat == 'other':
            unclassified.append(skill)

    print(f"\n=== Classification Results ===")
    total = 0
    for cat, skills in sorted(classified.items(), key=lambda x: -len(x[1])):
        print(f"  {cat}: {len(skills)} skills")
        total += len(skills)
    print(f"  Total: {total}")

    print(f"\n=== Unclassified ('other') — {len(unclassified)} skills ===")
    for s in unclassified:
        print(f"  {s}")

    # Now move them
    print(f"\n=== Moving skills to category directories ===")
    moves = 0
    errors = 0

    for cat, skills in classified.items():
        cat_path = os.path.join(str(BASE), cat)
        os.makedirs(cat_path, exist_ok=True)

        for skill in skills:
            src = os.path.join(str(BASE), skill)
            dst = os.path.join(cat_path, skill)

            if os.path.exists(dst):
                print(f"  SKIP (exists): {skill} -> {cat}/{skill}")
                errors += 1
                continue

            # Use git mv for proper tracking
            rel_src = f"collection/skills/{skill}"
            rel_dst = f"collection/skills/{cat}/{skill}"

            result = subprocess.run(
                ["git", "mv", rel_src, rel_dst],
                cwd=str(REPO_ROOT),
                capture_output=True, text=True
            )

            if result.returncode == 0:
                moves += 1
                if moves % 100 == 0:
                    print(f"  Progress: {moves} moved...")
            else:
                print(f"  ERROR moving {skill}: {result.stderr.strip()}")
                errors += 1

    print(f"\nDone: {moves} skills moved, {errors} errors")


if __name__ == "__main__":
    main()
